### ISSUE TITLE
Please add epvtotal from the summary data as sensor

### ISSUE THREAD

**Issue by paulbusse** [CharlesGillanders/homeassistant-alphaESS#145]
Hello,

I use the epvtotal to notify me that it is (about) time to request for a new certificate (Belgian thing).
I found that  using daily generation does not work if the Alphaess api is not available. Using the total picks up when the api is accessable again. E.g.

Day 1: daily 10 kWh; total 5000kWh
Day 2: [API down] (but a production of 10kWh)
Day 3: [API down] (but a production of 10kWh)
Day 1: daily 10 kWh; total 5040kWh

Using the day production I would miss the 20kWh from days 2 and 3.
Using the total production I still can see that the production of my solar panels is 40kWh.

Thanks

**Comment by Poshy163** [comment]
@paulbusse the PR is open, there is still a few other sensors that need to be added (in relation to EV charging) and then a new version will be released. if you know how to manually add code to the HACS integration in feel free to through the custom_components folder, otherwise it should be released soon*

**Comment by paulbusse** [comment]
Thanks and sorry for missing the PR.

**Comment by Poshy163** [comment]
Haha no stress, you didnt miss any PR, i made it shortly after you made this issue 😄
