### ISSUE TITLE
Use of TCP Modbus?

### ISSUE THREAD

**Issue by sebastianmachon** [CharlesGillanders/homeassistant-alphaESS#72]
Hi,
Have you tried to use the integrated Modbus TCP?
The used API needs a working Alpha API and internet connectivity.

Modbus TCP works local.

**Comment by dry** [comment]
See https://github.com/dxoverdy/Alpha2MQTT

**Comment by Spookster** [comment]
Works well :)

**Comment by Spookster** [comment]
One idea that I picked up from Daniels work was the use of ApexCharts to display data. It can be applied to Charles work as well to duplicate Alphas charts. I wish Id seen it sooner :)

![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/982535/d57b473d-473c-42fa-9625-f930fa37e0cd)

**Comment by aw1604** [comment]
Hello, I think what sebastian meant was a direct tcp modbus approach since for example the Smile-T10 now supports native modbus/tcp over the network. You can directly pull all data using the HA "modbus tcp" integration (and set too). 
Is there a way to re-write the AlphaESS integration to use HA internal modbus sensor data instead of relying on external mqtt and serial-to-network controllers (as they shouldn't be needed anymore) ?
I am not a coder myself, but willing to sponsor development..
Best Regards, Andreas
